namespace ParsMedeQ.Contracts.UserContracts.SigninContracts.SigninWithMobileContracts.SendOtpToExistingMobileContracts;

public readonly record struct SendOtpToExistingMobileApiRequest(string Mobile);

