namespace ParsMedeq.Application.Features.UserFeatures.SigninFeature.SigninWithMobileFeature.SendOtpToExistingMobileFeature;

public readonly record struct SendOtpToExistingMobileCommandResponse(string Otp);
