CREATE TABLE [dbo].[Service]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[TypeId] [tinyint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Service] ADD CONSTRAINT [PK_Service] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
