namespace EShop.Application.Features.EShopFeatures.UserFeatures.SigninFeature.SigninWithMobileFeature.SendOtpFeature;

public readonly record struct SigninWithMobileSendOtpCommandResponse(string Otp);
